T: 3
act: relu
amsgrad: false
batchid: 6
batchimage: 8
batchtest: 32
beta1: 0.9
beta2: 0.999
bnneck: false
config: ""
cosine_annealing: false
cpu: false
cuhk03_labeled: false
cutout: false
dampening: 0
data_test: market1501
data_train: market1501
datadir: /media/CityFlow/reid/reid/
decay_type: step_50_80_110
drop_block: false
epochs: 2
epsilon: 1.0e-08
feat_inference: after
feats: 512
gamma: 0.1
h_ratio: 0.3
height: 384
if_labelsmooth: true
loss: 0.5*CrossEntropy+0.5*MSLoss
lr: 0.0006
lr_decay: 60
margin: 0.7
model: LMBN_n
momentum: 0.9
nGPU: 1
nThread: 8
nep_id: ""
nesterov: false
num_anchors: 1
num_classes: 751
optimizer: ADAM
parts: 6
pcb_different_lr: true
pool: avg
probability: 0.5
random_erasing: true
reset: false
sampler: true
test_every: 10
w_cosine_annealing: true
w_ratio: 1.0
warmup: constant
weight_decay: 0.0005
width: 128
wandb: false
wandb_name: ""
